name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    permissions:
        contents: read
        pull-requests: write
        issues: write
        checks: write
    uses: f-pms/Devops/.github/workflows/ci.yaml@feature/lint-pr
    secrets:
        token: ${{ secrets.GITHUB_TOKEN }}
    with:
        prepare-command: echo "Preparing...!!!!"
        build-command: echo "Building...!!!!"
        test-command: echo "Testing...!!!"