name: CI
on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    uses: f-pms/Devops/.github/workflows/ci.yaml@master
    with:
      prepare-command: yarn prepare
      build-command: yarn build
      test-command: echo "Testing...!"
