name: CI
on:
  pull_request:
    branches:
      - master

permissions: write-all

jobs:
  ci:
    uses: f-pms/Devops/.github/workflows/ci.yaml@feature/lint-pr
    with:
        prepare-command: echo "Preparing...!!!!"
        build-command: echo "Building...!!!!"
        test-command: echo "Testing...!!!"