name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  ci:
    uses: f-pms/Devops/.github/workflows/ci.yaml@huynn/linter
