name: Manual Release

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: Make a choice
        options:
          - major
          - minor
          - patch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Bump version and tag
      id: bump_version
      uses: 'phips28/gh-action-bump-version@v11.0.0'
      with:
        tag-prefix: ''
        target-branch: 'master'
        minor-wording: 'minor'
        major-wording: 'major'
        patch-wording: 'patch'
        version-type: ${{ github.event.inputs.versionType }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
